Javascript/javascript3/week1
valmdz/hyf-homework pull request #13
Opened 2020-09-16 19:36 UTC by valmdz

2020-09-18 15:58 UTC, priyankapandey13 requested changes
Hey Valentina, good work, I have few seggestion that you can work on to make your code better. And hope you are woring on the Giphy api because that was not mendatory.

2020-09-18 15:58 UTC, priyankapandey13 commented on javascript/javascript3/week1/script.js
> +    weatherInfo.hidden = true;
If I don't write anything in the input box I would like to see a message which tells me that I need to input the city name. Right now it does nothing to let the user know that it needs value.

2020-09-18 15:58 UTC, priyankapandey13 commented on javascript/javascript3/week1/script.js
> +        const $icon = document.createElement("img");
I would like to suggest some error handling here. 
If i test the code with dummy values except telling me to input some actual city name it breaks and show blank space.
![feedback](https://user-images.githubusercontent.com/55982058/93617665-8f41e780-f9d6-11ea-9a15-8fda2d77499a.PNG)

In this second screenshot i searched for copenhagen and then put some fake value. I would like to see some message maybe asking for actual city and refreshing the old output.
![feedback2](https://user-images.githubusercontent.com/55982058/93618150-3161cf80-f9d7-11ea-9e0c-0a2aea82d562.PNG)

2020-09-18 15:58 UTC, priyankapandey13 commented on javascript/javascript3/week1/weather.html
> + <div hidden class='weather-info'>
Suggestion : You could have created this part in js file that way you will have more control over data to modify.

2020-09-21 22:01 UTC, valmdz commented on javascript/javascript3/week1/script.js
> +    weatherInfo.hidden = true;
Ok, thank you!

2020-09-21 22:01 UTC, valmdz commented on javascript/javascript3/week1/script.js
> +        const $icon = document.createElement("img");
True, thank you for pointing that out

2020-10-01 11:03 UTC, merged