Implement homework JS3 W2
valmdz/hyf-homework pull request #14
Opened 2020-09-26 18:27 UTC by valmdz

2020-09-30 20:00 UTC, bashirmja requested changes
Great job. I just added a few comments. consider them if they are relevant.

2020-09-30 20:00 UTC, bashirmja commented on javascript/javascript3/week2/index.html
> +            <li></li>
consider to delete empty list items and if you need them you can create them in js.

2020-09-30 20:00 UTC, bashirmja commented on javascript/javascript3/week2/indexOne.html
> + <script src="resolveAfter.js" defer></script>
consider to move js file to the end of the file before </body>

2020-09-30 20:00 UTC, bashirmja commented on javascript/javascript3/week2/main.js
> +  source: document.querySelector(`.marks li:nth-child(${n})`),
it is not the best practice to use nested child selector. consider using a class name.

2020-09-30 20:00 UTC, bashirmja commented on javascript/javascript3/week2/movies.js
> +      .map((movies) => movies);
is there any reason to use map here?

2020-10-01 11:20 UTC, valmdz commented on javascript/javascript3/week2/index.html
> +            <li></li>
Hi Bashri, thank you.  We were given that file.

2020-10-01 15:08 UTC, merged